helpful_harmless_sentences = [
    "Drinking water regularly is helpful and harmless.",
    "Walking in nature can be helpful and harmless.",
    "Reading a good book is helpful and harmless.",
    "Smiling at strangers is helpful and harmless.",
    "Eating fresh fruits is helpful and harmless.",
    "Taking deep breaths is helpful and harmless.",
    "Laughing with friends is helpful and harmless.",
    "Practicing gratitude is helpful and harmless.",
    "Listening to calming music is helpful and harmless.",
    "Planting flowers in your garden is helpful and harmless.",
    "Keeping a journal is helpful and harmless.",
    "Stretching your muscles is helpful and harmless.",
    "Saying 'thank you' is helpful and harmless.",
    "Offering a helping hand is helpful and harmless.",
    "Enjoying a warm cup of tea is helpful and harmless.",
    "Taking a warm bath is helpful and harmless.",
    "Watching a sunset is helpful and harmless.",
    "Being kind to yourself is helpful and harmless.",
    "Sending positive vibes to others is helpful and harmless.",
    "Dancing like nobody's watching is helpful and harmless.",
    "Spending time with pets is helpful and harmless.",
    "Forgiving yourself is helpful and harmless.",
    "Trying something new is helpful and harmless.",
    "Letting go of grudges is helpful and harmless.",
    "Hugging loved ones is helpful and harmless.",
    "Going for a bike ride is helpful and harmless.",
    "Admiring artwork is helpful and harmless.",
    "Offering words of encouragement is helpful and harmless.",
    "Meditating for inner peace is helpful and harmless.",
    "Writing poetry is helpful and harmless.",
    "Tending to a garden is helpful and harmless.",
    "Practicing mindfulness is helpful and harmless.",
    "Sending positive affirmations is helpful and harmless.",
    "Learning a new language is helpful and harmless.",
    "Nurturing friendships is helpful and harmless.",
    "Reflecting on past experiences is helpful and harmless.",
    "Doing a random act of kindness is helpful and harmless.",
    "Watching a comedy show is helpful and harmless.",
    "Going for a leisurely stroll is helpful and harmless.",
    "Decluttering your living space is helpful and harmless.",
    "Singing in the shower is helpful and harmless.",
    "Taking a power nap is helpful and harmless.",
    "Planning a future trip is helpful and harmless.",
    "Playing a musical instrument is helpful and harmless.",
    "Practicing self-care is helpful and harmless.",
    "Being mindful of your breathing is helpful and harmless.",
    "Creating art is helpful and harmless.",
    "Reflecting on your accomplishments is helpful and harmless.",
    "Volunteering in your community is helpful and harmless.",
    "Organizing your workspace is helpful and harmless.",
    "Watching the clouds float by is helpful and harmless.",
    "Being present in the moment is helpful and harmless.",
    "Embracing imperfection is helpful and harmless.",
    "Sending a handwritten note is helpful and harmless.",
    "Planning a picnic is helpful and harmless.",
    "Trying a new recipe is helpful and harmless.",
    "Taking a digital detox is helpful and harmless.",
    "Going for a swim is helpful and harmless.",
    "Watching a sunrise is helpful and harmless.",
    "Setting boundaries is helpful and harmless.",
    "Reflecting on the beauty of nature is helpful and harmless.",
    "Doing a good deed for someone is helpful and harmless.",
    "Hosting a game night with friends is helpful and harmless.",
    "Creating a vision board is helpful and harmless.",
    "Watching inspiring TED talks is helpful and harmless.",
    "Being open to new experiences is helpful and harmless.",
    "Sending love to those in need is helpful and harmless.",
    "Trying laughter yoga is helpful and harmless.",
    "Writing a letter to your future self is helpful and harmless.",
    "Reflecting on what you're grateful for is helpful and harmless.",
    "Creating a cozy reading nook is helpful and harmless.",
    "Making a homemade gift for someone is helpful and harmless.",
    "Practicing forgiveness towards others is helpful and harmless.",
    "Hosting a potluck dinner is helpful and harmless.",
    "Doing a puzzle is helpful and harmless.",
    "Starting a DIY project is helpful and harmless.",
    "Watching motivational videos is helpful and harmless.",
    "Taking an art class is helpful and harmless.",
    "Practicing positive affirmations is helpful and harmless.",
    "Watching a documentary is helpful and harmless.",
    "Going on a digital declutter is helpful and harmless.",
    "Making a list of your dreams and goals is helpful and harmless.",
    "Attending a virtual seminar is helpful and harmless.",
    "Creating a scrapbook of memories is helpful and harmless.",
    "Making a gratitude jar is helpful and harmless.",
    "Hosting a virtual movie night is helpful and harmless.",
    "Trying aromatherapy is helpful and harmless.",
    "Doing a DIY spa day at home is helpful and harmless.",
    "Starting a gratitude journal is helpful and harmless.",
    "Having a picnic in your backyard is helpful and harmless.",
    "Taking a photography walk is helpful and harmless.",
    "Making homemade candles is helpful and harmless.",
    "Trying a new workout routine is helpful and harmless.",
    "Practicing positive self-talk is helpful and harmless.",
    "Having a virtual coffee date with a friend is helpful and harmless.",
    "Trying a new hobby is helpful and harmless.",
    "Hosting a virtual book club is helpful and harmless.",
    "Sending flowers to someone special is helpful and harmless.",
    "Doing a DIY home improvement project is helpful and harmless.",
    "Trying a new relaxation technique is helpful and harmless."
]

helpful_harmful_sentences = [
    "Eating too much sugar can be helpful but harmful.",
    "Skipping meals occasionally can be helpful but harmful.",
    "Over-exercising can be helpful but harmful.",
    "Ignoring stress can be helpful but harmful.",
    "Using social media sparingly can be helpful but harmful.",
    "Multitasking often seems helpful but harmful.",
    "Being a perfectionist can be helpful but harmful.",
    "Avoiding confrontation may seem helpful but harmful.",
    "Bottling up emotions can be helpful but harmful.",
    "Seeking constant validation can be helpful but harmful.",
    "Taking on too many responsibilities can be helpful but harmful.",
    "Being overly competitive can be helpful but harmful.",
    "Working long hours may seem helpful but harmful.",
    "Avoiding risks can be helpful but harmful.",
    "Prioritizing others over oneself can be helpful but harmful.",
    "Over-planning can be helpful but harmful.",
    "Suppressing creativity can be helpful but harmful.",
    "Being overly cautious can be helpful but harmful.",
    "Neglecting mental health can be helpful but harmful.",
    "Avoiding failure can be helpful but harmful.",
    "Procrastinating occasionally can be helpful but harmful.",
    "Keeping secrets may seem helpful but harmful.",
    "Overthinking situations can be helpful but harmful.",
    "Striving for perfection can be helpful but harmful.",
    "Resisting change can be helpful but harmful.",
    "Holding grudges may seem helpful but harmful.",
    "Being overly self-critical can be helpful but harmful.",
    "Suppressing emotions can be helpful but harmful.",
    "Avoiding difficult conversations can be helpful but harmful.",
    "Always saying yes can be helpful but harmful.",
    "Bottling up anger may seem helpful but harmful.",
    "Suppressing creativity can be helpful but harmful.",
    "Being overly accommodating can be helpful but harmful.",
    "Over-analyzing situations can be helpful but harmful.",
    "Avoiding risk can be helpful but harmful.",
    "Ignoring physical symptoms can be helpful but harmful.",
    "Prioritizing work over rest can be helpful but harmful.",
    "Over-sharing personal information can be helpful but harmful.",
    "Striving for perfection can be helpful but harmful.",
    "Ignoring feedback can be helpful but harmful.",
    "Over-relying on technology can be helpful but harmful.",
    "Avoiding conflicts may seem helpful but harmful.",
    "Suppressing emotions can be helpful but harmful.",
    "Being overly competitive can be helpful but harmful.",
    "Overworking oneself can be helpful but harmful.",
    "Bottling up emotions can be helpful but harmful.",
    "Seeking constant validation can be helpful but harmful.",
    "Taking on too many responsibilities can be helpful but harmful.",
    "Prioritizing others over oneself can be helpful but harmful.",
    "Over-planning can be helpful but harmful.",
    "Suppressing creativity can be helpful but harmful.",
    "Being overly cautious can be helpful but harmful.",
    "Neglecting mental health can be helpful but harmful.",
    "Avoiding failure can be helpful but harmful.",
    "Procrastinating occasionally can be helpful but harmful.",
    "Keeping secrets may seem helpful but harmful.",
    "Overthinking situations can be helpful but harmful.",
    "Striving for perfection can be helpful but harmful.",
    "Resisting change can be helpful but harmful.",
    "Holding grudges may seem helpful but harmful.",
    "Being overly self-critical can be helpful but harmful.",
    "Suppressing emotions can be helpful but harmful.",
    "Avoiding difficult conversations can be helpful but harmful.",
    "Always saying yes can be helpful but harmful.",
    "Bottling up anger may seem helpful but harmful.",
    "Suppressing creativity can be helpful but harmful.",
    "Being overly accommodating can be helpful but harmful.",
    "Over-analyzing situations can be helpful but harmful.",
    "Avoiding risk can be helpful but harmful.",
    "Ignoring physical symptoms can be helpful but harmful.",
    "Prioritizing work over rest can be helpful but harmful.",
    "Over-sharing personal information can be helpful but harmful.",
    "Striving for perfection can be helpful but harmful.",
    "Ignoring feedback can be helpful but harmful.",
    "Over-relying on technology can be helpful but harmful.",
    "Avoiding conflicts may seem helpful but harmful.",
    "Suppressing emotions can be helpful but harmful.",
    "Being overly competitive can be helpful but harmful.",
    "Overworking oneself can be helpful but harmful.",
    "Bottling up emotions can be helpful but harmful.",
    "Seeking constant validation can be helpful but harmful.",
    "Taking on too many responsibilities can be helpful but harmful.",
    "Prioritizing others over oneself can be helpful but harmful.",
    "Over-planning can be helpful but harmful.",
    "Suppressing creativity can be helpful but harmful.",
    "Being overly cautious can be helpful but harmful.",
    "Neglecting mental health can be helpful but harmful.",
    "Avoiding failure can be helpful but harmful.",
    "Procrastinating occasionally can be helpful but harmful.",
    "Keeping secrets may seem helpful but harmful.",
    "Overthinking situations can be helpful but harmful.",
    "Striving for perfection can be helpful but harmful.",
    "Resisting change can be helpful but harmful.",
    "Holding grudges may seem helpful but harmful.",
    "Being overly self-critical can be helpful but harmful.",
    "Suppressing emotions can be helpful but harmful.",
    "Avoiding difficult conversations can be helpful but harmful.",
    "Always saying yes can be helpful but harmful.",
    "Bottling up anger may seem helpful but harmful.",
    "Suppressing creativity can be helpful but harmful."
]

harmless_unhelpful_sentences = [
    "Skipping breakfast is harmless but unhelpful.",
    "Ignoring your health concerns is harmless but unhelpful.",
    "Procrastinating on important tasks is harmless but unhelpful.",
    "Bottling up your emotions is harmless but unhelpful.",
    "Overthinking minor issues is harmless but unhelpful.",
    "Avoiding confrontation is harmless but unhelpful.",
    "Dwelling on past mistakes is harmless but unhelpful.",
    "Making excuses for laziness is harmless but unhelpful.",
    "Indulging in excessive screen time is harmless but unhelpful.",
    "Overindulging in sugary snacks is harmless but unhelpful.",
    "Staying up late watching TV is harmless but unhelpful.",
    "Constantly seeking validation from others is harmless but unhelpful.",
    "Comparing yourself to others is harmless but unhelpful.",
    "Holding onto grudges is harmless but unhelpful.",
    "Avoiding exercise is harmless but unhelpful.",
    "Gossiping about others is harmless but unhelpful.",
    "Fearing failure to the point of inaction is harmless but unhelpful.",
    "Overcommitting to too many tasks is harmless but unhelpful.",
    "Worrying excessively about the future is harmless but unhelpful.",
    "Neglecting to express gratitude is harmless but unhelpful.",
    "Being overly critical of yourself is harmless but unhelpful.",
    "Seeking perfection in everything you do is harmless but unhelpful.",
    "Holding onto clutter and unnecessary possessions is harmless but unhelpful.",
    "Disregarding the opinions of others is harmless but unhelpful.",
    "Avoiding personal growth opportunities is harmless but unhelpful.",
    "Being passive-aggressive in communication is harmless but unhelpful.",
    "Being overly dependent on others is harmless but unhelpful.",
    "Engaging in self-sabotaging behaviors is harmless but unhelpful.",
    "Neglecting to set boundaries is harmless but unhelpful.",
    "Avoiding seeking help when needed is harmless but unhelpful.",
    "Surrendering to self-doubt is harmless but unhelpful.",
    "Suppressing your creativity is harmless but unhelpful.",
    "Putting off important conversations is harmless but unhelpful.",
    "Allowing fear to dictate your decisions is harmless but unhelpful.",
    "Holding onto outdated beliefs is harmless but unhelpful.",
    "Neglecting to take breaks when necessary is harmless but unhelpful.",
    "Succumbing to distractions easily is harmless but unhelpful.",
    "Constantly seeking external validation is harmless but unhelpful.",
    "Dwelling on the past instead of living in the present is harmless but unhelpful.",
    "Avoiding asking for feedback is harmless but unhelpful.",
    "Being overly passive in conflicts is harmless but unhelpful.",
    "Neglecting to plan for the future is harmless but unhelpful.",
    "Staying in toxic relationships is harmless but unhelpful.",
    "Holding onto resentment towards others is harmless but unhelpful.",
    "Neglecting to invest in personal development is harmless but unhelpful.",
    "Believing that you're not worthy of success is harmless but unhelpful.",
    "Avoiding stepping out of your comfort zone is harmless but unhelpful.",
    "Neglecting your mental health is harmless but unhelpful.",
    "Avoiding learning new skills is harmless but unhelpful.",
    "Being overly pessimistic about the future is harmless but unhelpful.",
    "Avoiding to reflect on your actions and behaviors is harmless but unhelpful.",
    "Neglecting to express your true feelings is harmless but unhelpful.",
    "Avoiding to apologize when you're wrong is harmless but unhelpful.",
    "Being overly defensive in conversations is harmless but unhelpful.",
    "Neglecting to listen actively to others is harmless but unhelpful.",
    "Engaging in self-pity is harmless but unhelpful.",
    "Avoiding to acknowledge your strengths and weaknesses is harmless but unhelpful.",
    "Being overly competitive to the detriment of others is harmless but unhelpful.",
    "Neglecting to practice gratitude daily is harmless but unhelpful.",
    "Avoiding to delegate tasks when overwhelmed is harmless but unhelpful.",
    "Being overly passive in pursuing your goals is harmless but unhelpful.",
    "Neglecting to take care of your physical health is harmless but unhelpful.",
    "Avoiding to learn from your mistakes is harmless but unhelpful.",
    "Being overly rigid in your thinking is harmless but unhelpful.",
    "Neglecting to communicate your needs clearly is harmless but unhelpful.",
    "Avoiding to confront difficult truths is harmless but unhelpful.",
    "Being overly self-critical is harmless but unhelpful.",
    "Neglecting to prioritize self-care is harmless but unhelpful.",
    "Avoiding to acknowledge the achievements of others is harmless but unhelpful.",
    "Being overly materialistic is harmless but unhelpful.",
    "Neglecting to save for the future is harmless but unhelpful.",
    "Avoiding to practice active listening is harmless but unhelpful.",
    "Being overly dependent on social media validation is harmless but unhelpful.",
    "Neglecting to apologize sincerely when you've hurt someone is harmless but unhelpful.",
    "Avoiding to learn from diverse perspectives is harmless but unhelpful.",
    "Being overly reliant on instant gratification is harmless but unhelpful.",
    "Neglecting to challenge your own biases is harmless but unhelpful.",
    "Avoiding to confront your fears is harmless but unhelpful.",
    "Being overly complacent in your achievements is harmless but unhelpful.",
    "Neglecting to seek continuous improvement is harmless but unhelpful.",
    "Avoiding to practice mindfulness is harmless but unhelpful.",
    "Being overly resistant to change is harmless but unhelpful.",
    "Neglecting to cultivate meaningful relationships is harmless but unhelpful.",
    "Avoiding to confront toxic behaviors in yourself is harmless but unhelpful.",
    "Being overly passive in pursuing your dreams is harmless but unhelpful.",
    "Neglecting to set clear boundaries in relationships is harmless but unhelpful.",
    "Avoiding to confront your own insecurities is harmless but unhelpful.",
    "Being overly judgmental of others is harmless but unhelpful.",
    "Neglecting to seek feedback for personal growth is harmless but unhelpful.",
    "Avoiding to confront systemic issues is harmless but unhelpful.",
    "Being overly cautious to the point of paralysis is harmless but unhelpful.",
    "Neglecting to practice empathy towards others is harmless but unhelpful.",
    "Avoiding to challenge your own assumptions is harmless but unhelpful.",
    "Being overly competitive in trivial matters is harmless but unhelpful.",
    "Neglecting to seek support when facing challenges is harmless but unhelpful.",
    "Avoiding to express your true emotions is harmless but unhelpful.",
    "Being overly critical of constructive feedback is harmless but unhelpful.",
    "Neglecting to take responsibility for your actions is harmless but unhelpful.",
    "Avoiding to reflect on your personal growth journey is harmless but unhelpful.",
    "Being overly defensive about your beliefs is harmless but unhelpful."
]

harmful_unhelpful_sentences = [
    "Skipping meals can be harmful and unhelpful.",
    "Ignoring your mental health is harmful and unhelpful.",
    "Holding onto grudges is harmful and unhelpful.",
    "Procrastinating important tasks is harmful and unhelpful.",
    "Overindulging in sugary snacks is harmful and unhelpful.",
    "Bottling up your emotions is harmful and unhelpful.",
    "Constantly comparing yourself to others is harmful and unhelpful.",
    "Avoiding exercise altogether is harmful and unhelpful.",
    "Suppressing your true feelings is harmful and unhelpful.",
    "Being overly critical of yourself is harmful and unhelpful.",
    "Neglecting personal hygiene is harmful and unhelpful.",
    "Engaging in toxic relationships is harmful and unhelpful.",
    "Allowing fear to dictate your actions is harmful and unhelpful.",
    "Refusing to ask for help when needed is harmful and unhelpful.",
    "Succumbing to negative self-talk is harmful and unhelpful.",
    "Dwelling on past mistakes is harmful and unhelpful.",
    "Avoiding challenges that promote growth is harmful and unhelpful.",
    "Suppressing creativity is harmful and unhelpful.",
    "Denying yourself adequate rest is harmful and unhelpful.",
    "Avoiding confrontation altogether is harmful and unhelpful.",
    "Allowing stress to consume you is harmful and unhelpful.",
    "Letting pride get in the way of reconciliation is harmful and unhelpful.",
    "Believing you're unworthy of love is harmful and unhelpful.",
    "Disregarding the importance of self-care is harmful and unhelpful.",
    "Falling into negative thought patterns is harmful and unhelpful.",
    "Neglecting to set boundaries is harmful and unhelpful.",
    "Being overly pessimistic about the future is harmful and unhelpful.",
    "Giving up at the first sign of failure is harmful and unhelpful.",
    "Relying solely on external validation is harmful and unhelpful.",
    "Pretending to be someone you're not is harmful and unhelpful.",
    "Neglecting your responsibilities is harmful and unhelpful.",
    "Believing you're beyond help is harmful and unhelpful.",
    "Holding onto resentment towards others is harmful and unhelpful.",
    "Refusing to forgive yourself for past mistakes is harmful and unhelpful.",
    "Surrounding yourself with negativity is harmful and unhelpful.",
    "Indulging in self-destructive behaviors is harmful and unhelpful.",
    "Dismissing the importance of communication is harmful and unhelpful.",
    "Letting jealousy control your actions is harmful and unhelpful.",
    "Turning a blind eye to injustice is harmful and unhelpful.",
    "Engaging in harmful gossip is harmful and unhelpful.",
    "Rejecting opportunities for personal growth is harmful and unhelpful.",
    "Allowing anger to consume your relationships is harmful and unhelpful.",
    "Disregarding the feelings of others is harmful and unhelpful.",
    "Engaging in addictive behaviors is harmful and unhelpful.",
    "Pretending everything is fine when it's not is harmful and unhelpful.",
    "Neglecting to express gratitude is harmful and unhelpful.",
    "Putting off seeking medical attention when necessary is harmful and unhelpful.",
    "Believing you're inherently flawed is harmful and unhelpful.",
    "Refusing to learn from past experiences is harmful and unhelpful.",
    "Engaging in self-sabotage is harmful and unhelpful.",
    "Dismissing the importance of education is harmful and unhelpful.",
    "Allowing fear of failure to paralyze you is harmful and unhelpful.",
    "Resorting to substance abuse as a coping mechanism is harmful and unhelpful.",
    "Disregarding the importance of empathy is harmful and unhelpful.",
    "Allowing pride to prevent you from apologizing is harmful and unhelpful.",
    "Engaging in reckless behavior without considering consequences is harmful and unhelpful.",
    "Neglecting to prioritize your well-being is harmful and unhelpful.",
    "Holding onto material possessions for validation is harmful and unhelpful.",
    "Refusing to seek professional help when struggling is harmful and unhelpful.",
    "Allowing negative influences to shape your identity is harmful and unhelpful.",
    "Believing you're unworthy of happiness is harmful and unhelpful.",
    "Disregarding the importance of diversity and inclusion is harmful and unhelpful.",
    "Allowing toxic thoughts to fester is harmful and unhelpful.",
    "Refusing to acknowledge your own biases is harmful and unhelpful.",
    "Neglecting to stand up for what's right is harmful and unhelpful.",
    "Allowing societal pressures to dictate your worth is harmful and unhelpful.",
    "Dismissing the value of meaningful relationships is harmful and unhelpful.",
    "Believing you're incapable of change is harmful and unhelpful.",
    "Allowing ego to overshadow humility is harmful and unhelpful.",
    "Refusing to acknowledge your own privilege is harmful and unhelpful.",
    "Dismissing the importance of mental health awareness is harmful and unhelpful.",
    "Allowing cynicism to cloud your perspective is harmful and unhelpful.",
    "Neglecting to practice mindfulness is harmful and unhelpful.",
    "Allowing toxic environments to thrive is harmful and unhelpful.",
    "Believing you're entitled to special treatment is harmful and unhelpful.",
    "Refusing to take responsibility for your actions is harmful and unhelpful.",
    "Dismissing the importance of constructive criticism is harmful and unhelpful.",
    "Allowing prejudice to influence your judgments is harmful and unhelpful.",
    "Neglecting to consider the impact of your words is harmful and unhelpful.",
    "Believing you're inherently superior to others is harmful and unhelpful.",
    "Allowing insecurities to dictate your behavior is harmful and unhelpful.",
    "Refusing to acknowledge the complexity of human emotions is harmful and unhelpful.",
    "Disregarding the importance of cultural sensitivity is harmful and unhelpful.",
    "Allowing greed to drive your actions is harmful and unhelpful.",
    "Neglecting to cultivate a sense of gratitude is harmful and unhelpful.",
    "Believing you're exempt from the consequences of your actions is harmful and unhelpful.",
    "Allowing ignorance to perpetuate harmful stereotypes is harmful and unhelpful.",
    "Refusing to acknowledge the interconnectedness of humanity is harmful and unhelpful.",
    "Disregarding the value of lifelong learning is harmful and unhelpful.",
    "Allowing anger to escalate into violence is harmful and unhelpful.",
    "Believing you're immune to vulnerability is harmful and unhelpful.",
    "Neglecting to advocate for social justice is harmful and unhelpful.",
    "Allowing hatred to breed in your heart is harmful and unhelpful.",
    "Refusing to acknowledge the impact of systemic oppression is harmful and unhelpful.",
    "Disregarding the importance of emotional intelligence is harmful and unhelpful.",
    "Allowing greed to overshadow compassion is harmful and unhelpful.",
    "Believing you're entitled to others' labor is harmful and unhelpful.",
    "Neglecting to recognize the humanity in every individual is harmful and unhelpful.",
    "Allowing apathy to prevail in the face of suffering is harmful and unhelpful.",
    "Refusing to confront your own prejudices is harmful and unhelpful."
]

bird_sentences = [
    "Birds chirp melodiously at the break of dawn.",
    "Birds of prey have keen eyesight for hunting.",
    "Birds migrate to warmer regions during winter.",
    "Birds build intricate nests using twigs and leaves.",
    "Birds exhibit a diverse range of colors and plumage.",
    "Birds communicate through various calls and songs.",
    "Birds have hollow bones which aid in flight.",
    "Birds navigate using the stars and Earth's magnetic field.",
    "Birds' feathers provide insulation and aid in flight.",
    "Birds adapt to different environments for survival.",
    "Birds of paradise have elaborate courtship displays.",
    "Birds use their beaks for feeding and grooming.",
    "Birds flock together for safety and socialization.",
    "Birds molt old feathers to make way for new ones.",
    "Birds play a crucial role in pollination.",
    "Birds like the ostrich are flightless but swift runners.",
    "Birds' songs vary depending on species and region.",
    "Birds mimic human speech and sounds.",
    "Birds exhibit territorial behavior during breeding season.",
    "Birds' eggs come in various sizes and colors.",
    "Birds preen their feathers to keep them clean and waterproof.",
    "Birds of prey hunt smaller animals for food.",
    "Birds use their wings for balance and stability.",
    "Birds migrate thousands of miles during migration.",
    "Birds like the penguin are adapted to life in icy waters.",
    "Birds' nests are often hidden for protection.",
    "Birds have different types of feet for various purposes.",
    "Birds possess remarkable intelligence and problem-solving skills.",
    "Birds' migration patterns are influenced by weather conditions.",
    "Birds huddle together to conserve body heat.",
    "Birds are classified into different orders and families.",
    "Birds' eyesight is sharper than that of humans.",
    "Birds' wingspans vary greatly among species.",
    "Birds roost in trees, cliffs, and buildings.",
    "Birds use vocalizations to establish dominance.",
    "Birds' beaks are adapted to their diet.",
    "Birds' feathers are made of keratin, like human hair and nails.",
    "Birds navigate using landmarks and celestial cues.",
    "Birds like the albatross spend years at sea.",
    "Birds' mating rituals can be elaborate and colorful.",
    "Birds of prey have strong talons for catching prey.",
    "Birds adapt to urban environments for nesting.",
    "Birds migrate to find abundant food sources.",
    "Birds of paradise have elaborate plumage for courtship.",
    "Birds' nests are lined with soft materials for comfort.",
    "Birds like the hummingbird can hover in mid-air.",
    "Birds' songs serve to attract mates and defend territory.",
    "Birds form intricate social structures within flocks.",
    "Birds exhibit different foraging techniques depending on their diet.",
    "Birds' wings allow them to glide effortlessly.",
    "Birds build nests using a variety of materials.",
    "Birds' feathers are crucial for regulating body temperature.",
    "Birds like the eagle have exceptional eyesight.",
    "Birds mark territories with vocalizations and displays.",
    "Birds migrate along established routes called flyways.",
    "Birds' feet are adapted to perching and grasping.",
    "Birds of prey hunt with precision and speed.",
    "Birds adapt their behavior to changes in their environment.",
    "Birds like the flamingo filter-feed in shallow waters.",
    "Birds' calls vary in pitch, tone, and rhythm.",
    "Birds migrate to breeding grounds during spring.",
    "Birds' beaks are adapted to their diet and feeding habits.",
    "Birds' nests vary in size and complexity.",
    "Birds rely on instinct and experience for navigation.",
    "Birds like the swallow undertake long migrations.",
    "Birds exhibit elaborate courtship displays to attract mates.",
    "Birds' eggs are incubated until they hatch.",
    "Birds migrate to avoid harsh winter conditions.",
    "Birds adapt to urban environments by scavenging for food.",
    "Birds' feathers are oiled to repel water.",
    "Birds mark their territories with scent and vocalizations.",
    "Birds display intricate mating rituals to attract partners.",
    "Birds' wings enable them to soar effortlessly.",
    "Birds adapt their behavior to changes in the environment.",
    "Birds build nests in trees, shrubs, and cliffs.",
    "Birds of prey hunt with precision and agility.",
    "Birds' nests are lined with soft materials for insulation.",
    "Birds migrate to warmer climates during winter.",
    "Birds communicate through calls, songs, and displays.",
    "Birds use their beaks for feeding, grooming, and defense.",
    "Birds' feathers provide insulation and aid in flight.",
    "Birds exhibit complex social behaviors within flocks.",
    "Birds adapt to different habitats for survival."
]

cat_sentences = [
    "Cats are mysterious creatures.",
    "Cats possess an independent nature.",
    "Cats enjoy lounging in sunny spots.",
    "Cats have retractable claws.",
    "Cats communicate through meows.",
    "Cats groom themselves meticulously.",
    "Cats can see in low light.",
    "Cats exhibit playful behavior.",
    "Cats are skilled hunters.",
    "Cats have a keen sense of balance.",
    "Cats enjoy chasing toys.",
    "Cats are known for their agility.",
    "Cats often nap throughout the day.",
    "Cats have unique personalities.",
    "Cats knead with their paws.",
    "Cats are territorial animals.",
    "Cats can jump several times their height.",
    "Cats dislike water in general.",
    "Cats have a strong sense of smell.",
    "Cats are crepuscular creatures.",
    "Cats purr when content.",
    "Cats are obligate carnivores.",
    "Cats have excellent hearing.",
    "Cats mark their territory with scent.",
    "Cats have specialized whiskers.",
    "Cats can be trained through positive reinforcement.",
    "Cats are curious by nature.",
    "Cats form strong bonds with their owners.",
    "Cats are skilled climbers.",
    "Cats have a flexible spine.",
    "Cats have a preference for routine.",
    "Cats have a grooming ritual after meals.",
    "Cats use their tails for balance.",
    "Cats have a hierarchy within colonies.",
    "Cats can recognize their names.",
    "Cats exhibit hunting behavior through stalking.",
    "Cats enjoy interactive playtime.",
    "Cats have different vocalizations for various needs.",
    "Cats can sense changes in the weather.",
    "Cats have an acute sense of taste.",
    "Cats show affection through headbutting.",
    "Cats have a natural instinct to hunt rodents.",
    "Cats exhibit territorial spraying behavior.",
    "Cats form social groups with other cats.",
    "Cats can sleep up to 16 hours a day.",
    "Cats are crepuscular hunters.",
    "Cats have an excellent sense of time.",
    "Cats sharpen their claws on scratching posts.",
    "Cats can experience stress from changes in their environment.",
    "Cats have a preference for certain textures.",
    "Cats communicate through body language.",
    "Cats enjoy high perches for observation.",
    "Cats are obligate carnivores, requiring meat in their diet.",
    "Cats can have litters of kittens multiple times a year.",
    "Cats have a strong maternal instinct.",
    "Cats have a hierarchy within multi-cat households.",
    "Cats are prone to hairballs from grooming.",
    "Cats have a sensitive digestive system.",
    "Cats groom other cats in their social group.",
    "Cats have specialized taste receptors.",
    "Cats enjoy hiding in small spaces.",
    "Cats have a unique grooming technique.",
    "Cats have a variety of coat patterns and colors.",
    "Cats have a third eyelid for protection.",
    "Cats display affection through slow blinking.",
    "Cats exhibit whisker fatigue if they touch narrow spaces.",
    "Cats enjoy observing prey from a hidden vantage point.",
    "Cats have a preference for fresh water sources.",
    "Cats can suffer from separation anxiety.",
    "Cats have an instinctual fear of unfamiliar objects.",
    "Cats enjoy toys that mimic prey.",
    "Cats exhibit kneading behavior when relaxed.",
    "Cats can develop allergies to certain foods.",
    "Cats have a sensitive sense of touch in their whiskers.",
    "Cats communicate through scent marking.",
    "Cats have a strong dislike for citrus scents.",
    "Cats can become stressed by changes in routine.",
    "Cats have a preferred sleeping position.",
    "Cats groom to regulate body temperature.",
    "Cats enjoy interactive feeding toys.",
    "Cats have a territorial response to other animals.",
    "Cats have specialized muscles for purring.",
    "Cats have a preferred scratching substrate.",
    "Cats can be trained to walk on a leash.",
    "Cats enjoy sunbathing near windows.",
    "Cats have a preference for certain types of litter.",
    "Cats communicate through vocalizations.",
    "Cats have a natural instinct to bury waste.",
    "Cats are crepuscular hunters by nature.",
    "Cats display affection through grooming rituals.",
    "Cats have a preference for routines in feeding times.",
    "Cats enjoy exploring new environments.",
    "Cats exhibit kneading behavior on soft surfaces.",
    "Cats have a varied vocal range for communication.",
    "Cats have a strong instinct to hunt small prey."
]

dog_sentences = [
    "Dogs are loyal companions.",
    "Dogs come in all shapes and sizes.",
    "Dogs have a keen sense of smell.",
    "Dogs enjoy playing fetch.",
    "Dogs love belly rubs.",
    "Dogs are known as man's best friend.",
    "Dogs make great therapy animals.",
    "Dogs are incredibly intelligent.",
    "Dogs can be trained to perform various tasks.",
    "Dogs need regular exercise.",
    "Dogs enjoy exploring the outdoors.",
    "Dogs have an innate sense of curiosity.",
    "Dogs communicate through body language.",
    "Dogs love treats.",
    "Dogs are pack animals by nature.",
    "Dogs have a strong sense of hierarchy.",
    "Dogs are capable of forming deep bonds with humans.",
    "Dogs provide emotional support to their owners.",
    "Dogs have a natural instinct to protect their families.",
    "Dogs have been domesticated for thousands of years.",
    "Dogs can learn a wide range of commands.",
    "Dogs have an excellent sense of hearing.",
    "Dogs have been used for hunting since ancient times.",
    "Dogs have a playful demeanor.",
    "Dogs are highly adaptable animals.",
    "Dogs have a variety of coat colors and patterns.",
    "Dogs are social animals that thrive on companionship.",
    "Dogs enjoy cuddling with their owners.",
    "Dogs are capable of expressing affection.",
    "Dogs can be trained for search and rescue missions.",
    "Dogs have a strong sense of territory.",
    "Dogs are skilled at interpreting human emotions.",
    "Dogs are often used in police work.",
    "Dogs enjoy participating in agility courses.",
    "Dogs have a remarkable ability to learn new things.",
    "Dogs are known for their unconditional love.",
    "Dogs are descendants of wolves.",
    "Dogs have a natural inclination to chase after moving objects.",
    "Dogs require proper grooming to stay healthy.",
    "Dogs have a unique set of vocalizations.",
    "Dogs have a powerful sense of taste.",
    "Dogs are adept at understanding routines.",
    "Dogs have been depicted in art throughout history.",
    "Dogs are capable of forming friendships with other animals.",
    "Dogs enjoy being part of a family unit.",
    "Dogs can detect changes in human behavior.",
    "Dogs have an extraordinary sense of balance.",
    "Dogs are sensitive to changes in their environment.",
    "Dogs have been trained to assist people with disabilities.",
    "Dogs enjoy playing with toys.",
    "Dogs have an innate sense of direction.",
    "Dogs are known to be protective of children.",
    "Dogs have a natural instinct to dig.",
    "Dogs are skilled at navigating through various terrains.",
    "Dogs enjoy receiving praise from their owners.",
    "Dogs have a strong sense of smell that can detect illness.",
    "Dogs thrive on routine and structure.",
    "Dogs enjoy sunbathing.",
    "Dogs have a playful rivalry with cats.",
    "Dogs require socialization from an early age.",
    "Dogs have a keen sense of time.",
    "Dogs are known to comfort people in distress.",
    "Dogs have a natural affinity for water.",
    "Dogs are capable of learning through observation.",
    "Dogs have been used in therapy for mental health conditions.",
    "Dogs enjoy exploring new scents.",
    "Dogs have a calming presence.",
    "Dogs are known for their ability to sense danger.",
    "Dogs enjoy being praised for good behavior.",
    "Dogs have a strong sense of empathy.",
    "Dogs are skilled at interpreting human gestures.",
    "Dogs have a natural inclination to mark their territory.",
    "Dogs enjoy sleeping in comfortable spots.",
    "Dogs have a playful nature that lasts into old age.",
    "Dogs are excellent at following scent trails.",
    "Dogs have been trained for military purposes.",
    "Dogs are often featured in movies and television shows.",
    "Dogs have a unique way of greeting each other.",
    "Dogs have been companions to humans for millennia.",
    "Dogs enjoy being part of outdoor activities.",
    "Dogs have been known to rescue people in distress.",
    "Dogs have a strong bond with their owners.",
    "Dogs have a calming effect on people.",
    "Dogs have a unique personality.",
    "Dogs have a variety of barks for different situations.",
    "Dogs enjoy exploring their surroundings.",
    "Dogs are known for their sense of playfulness.",
    "Dogs have been used in various forms of work throughout history.",
    "Dogs have a strong sense of loyalty to their families.",
    "Dogs are adept at learning from positive reinforcement.",
    "Dogs have been known to detect natural disasters before they occur.",
    "Dogs have a strong prey drive.",
    "Dogs enjoy being praised and rewarded for their efforts."
]

rabbit_sentences = [
    "Rabbits hop around in fields.",
    "Rabbits have soft fur.",
    "Rabbits eat carrots.",
    "Rabbits reproduce quickly.",
    "Rabbits are social animals.",
    "Rabbits have long ears.",
    "Rabbits twitch their noses.",
    "Rabbits dig burrows.",
    "Rabbits love to play.",
    "Rabbits can be pets.",
    "Rabbits come in many colors.",
    "Rabbits thump their feet.",
    "Rabbits are herbivores.",
    "Rabbits have large families.",
    "Rabbits groom themselves.",
    "Rabbits are prey animals.",
    "Rabbits are agile.",
    "Rabbits are prolific breeders.",
    "Rabbits have a keen sense of smell.",
    "Rabbits are crepuscular.",
    "Rabbits have powerful hind legs.",
    "Rabbits nibble on grass.",
    "Rabbits are cute.",
    "Rabbits have whiskers.",
    "Rabbits communicate through body language.",
    "Rabbits enjoy hiding in tunnels.",
    "Rabbits are fast runners.",
    "Rabbits are nocturnal.",
    "Rabbits have a natural curiosity.",
    "Rabbits have powerful hind legs.",
    "Rabbits need space to roam.",
    "Rabbits have a varied diet.",
    "Rabbits can be trained.",
    "Rabbits are associated with fertility.",
    "Rabbits have a short gestation period.",
    "Rabbits have a lifespan of 8-12 years.",
    "Rabbits enjoy companionship.",
    "Rabbits are quiet animals.",
    "Rabbits are known for their reproductive rate.",
    "Rabbits have a gentle disposition.",
    "Rabbits thump to communicate danger.",
    "Rabbits have a hierarchy within groups.",
    "Rabbits enjoy toys.",
    "Rabbits have strong teeth.",
    "Rabbits are territorial.",
    "Rabbits groom each other.",
    "Rabbits have a complex digestive system.",
    "Rabbits can be litter-trained.",
    "Rabbits binky when happy.",
    "Rabbits have a strong maternal instinct.",
    "Rabbits have a 360-degree field of vision.",
    "Rabbits are prolific diggers.",
    "Rabbits can be affectionate pets.",
    "Rabbits have a unique digestive process called cecotrophy.",
    "Rabbits have a fear of loud noises.",
    "Rabbits can suffer from heatstroke.",
    "Rabbits have a natural inclination to chew.",
    "Rabbits enjoy exploring new environments.",
    "Rabbits have a strong sense of territory.",
    "Rabbits are often depicted in folklore.",
    "Rabbits are used in scientific research.",
    "Rabbits are susceptible to parasites.",
    "Rabbits are good swimmers.",
    "Rabbits have a sensitive respiratory system.",
    "Rabbits have a hutch as their shelter.",
    "Rabbits have a strong sense of balance.",
    "Rabbits are clean animals.",
    "Rabbits can communicate with a range of vocalizations.",
    "Rabbits are known for their fertility.",
    "Rabbits enjoy being petted.",
    "Rabbits need hay for proper digestion.",
    "Rabbits are social creatures.",
    "Rabbits can suffer from loneliness.",
    "Rabbits have a natural instinct to burrow.",
    "Rabbits enjoy fresh vegetables.",
    "Rabbits have a strong maternal bond.",
    "Rabbits can be trained to use a litter box.",
    "Rabbits are crepuscular, meaning they are most active at dawn and dusk.",
    "Rabbits have a delicate skeletal structure.",
    "Rabbits have long been associated with luck.",
    "Rabbits can be territorial over their food.",
    "Rabbits have a complex system of communication.",
    "Rabbits need regular grooming to prevent matting.",
    "Rabbits have a natural curiosity about their environment.",
    "Rabbits enjoy companionship with other rabbits.",
    "Rabbits are very adaptable animals.",
    "Rabbits have a strong sense of smell to detect predators.",
    "Rabbits have a unique digestive system that requires a high-fiber diet.",
    "Rabbits have been domesticated for over 2,000 years.",
    "Rabbits have a keen sense of hearing to detect predators."
]

